version: 2

jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  release:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Login, Build, and Push
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker build -t $DOCKER_USERNAME/django.nv .
            docker push $DOCKER_USERNAME/django.nv

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail                   # Even if the job fails, continue to the next stages

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a 'deploy' step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test
      - release:
          requires:
            - build
            - test
      - integration:
          requires:
            - release
      - prod:
          type: approval
          requires:
            - integration
